"""sdsapi

Revision ID: 44e177a5377f
Revises: 
Create Date: 2021-08-26 11:56:30.444959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44e177a5377f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SDS',
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('mis', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('mis')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('SDS')
    # ### end Alembic commands ###
